<?php

namespace App\Service;

use App\Entity\Categories;
use App\Entity\Editeur;
use App\Entity\Emission;
use App\Entity\ProgrammationRuleSlot;
use App\Entity\Theme;
use App\Entity\User;
use App\Repository\ThemeRepository;
use App\Repository\UserRepository;
use Doctrine\DBAL\Connection;
use Doctrine\ORM\EntityManagerInterface;

class LiveEmissionCreator
{
    public function __construct(
        private readonly EntityManagerInterface $em,
        private readonly Connection $connection,
        private readonly UserRepository $userRepository,
        private readonly ThemeRepository $themeRepository,
    ) {}

    public function createFromSlot(ProgrammationRuleSlot $slot, \DateTimeInterface $startsAt): Emission
    {
        $rule = $slot->getRule();

        if ($rule === null) {
            throw new \RuntimeException('Impossible de créer un direct : ce créneau n’est lié à aucune règle.');
        }

        $category = $rule->getCategory();

        if ($category === null) {
            throw new \RuntimeException('Impossible de créer un direct : la règle n’a pas de catégorie.');
        }

        $users = $this->findUsersForCategory((int) $category->getId());

        $theme = $this->resolveDefaultTheme();
        $editeur = $this->resolveEditorForCategory($category);

        $emission = new Emission();

        $emission
            ->setTitre($this->buildTitle($category->getTitre(), $startsAt))
            ->setKeyword('')
            ->setDatepub(\DateTime::createFromInterface($startsAt))
            ->setRef('')
            ->setDuree($slot->getDurationMinutes() ?? 15)
            ->setUrl(null)
            ->setDescriptif($this->buildDescription($category->getTitre(), $startsAt, true))
            ->setCategorie($category)
            ->setTheme($theme)
            ->setEditeur($editeur)
            ->setAutoGeneratedForSlot($slot)
            ->setAutoGeneratedForStartsAt(\DateTime::createFromInterface($startsAt))
            ->markAsAutoGenerated();

        foreach ($users as $user) {
            $emission->addUser($user);
        }

        $this->em->persist($emission);
        $this->em->flush();

        return $emission;
    }

    public function createManualForCategory(Categories $category, \DateTimeInterface $startsAt): Emission
    {
        if (!$category->isActive() || $category->isSoftDelete()) {
            throw new \RuntimeException('Impossible de créer un direct manuel : catégorie inactive ou supprimée.');
        }

        $users = $this->findUsersForCategory((int) $category->getId());

        $theme = $this->resolveDefaultTheme();
        $editeur = $this->resolveEditorForCategory($category);

        $emission = new Emission();

        $emission
            ->setTitre($this->buildManualLiveTitle($category->getTitre(), $startsAt))
            ->setKeyword('')
            ->setDatepub(\DateTime::createFromInterface($startsAt))
            ->setRef('')
            ->setDuree($this->resolveManualLiveDuration($category))
            ->setUrl(null)
            ->setDescriptif($this->buildDescription($category->getTitre(), $startsAt, false))
            ->setCategorie($category)
            ->setTheme($theme)
            ->setEditeur($editeur)
            ->setAutoGeneratedForSlot(null)
            ->setAutoGeneratedForStartsAt(\DateTime::createFromInterface($startsAt))
            ->markAsAutoGenerated();

        foreach ($users as $user) {
            $emission->addUser($user);
        }

        $this->em->persist($emission);
        $this->em->flush();

        return $emission;
    }

    /**
     * @return User[]
     */
    private function findUsersForCategory(int $categoryId): array
    {
        $rows = $this->connection->fetchAllAssociative(
            'SELECT user_id FROM categories_user WHERE categories_id = :categoryId',
            ['categoryId' => $categoryId]
        );

        $userIds = [];

        foreach ($rows as $row) {
            if (isset($row['user_id'])) {
                $userIds[] = (int) $row['user_id'];
            }
        }

        $userIds = array_values(array_unique($userIds));

        if ($userIds === []) {
            return [];
        }

        /** @var User[] $users */
        $users = $this->userRepository->findBy(['id' => $userIds]);

        return $users;
    }

    private function resolveDefaultTheme(): Theme
    {
        $theme = $this->themeRepository->find(15);

        if (!$theme instanceof Theme) {
            throw new \RuntimeException('Thème par défaut introuvable.');
        }

        return $theme;
    }

    private function resolveEditorForCategory(Categories $category): ?Editeur
    {
        return $category->getEditeur();
    }

    private function resolveManualLiveDuration(Categories $category): int
    {
        $duration = $category->getDuree();

        if (\is_int($duration) && $duration > 0) {
            return $duration;
        }

        return 60;
    }

    private function buildTitle(string $categoryTitle, \DateTimeInterface $startsAt): string
    {
        return sprintf(
            'Direct du %s - %s',
            $startsAt->format('d/m/Y'),
            $categoryTitle
        );
    }

    private function buildManualLiveTitle(string $categoryTitle, \DateTimeInterface $startsAt): string
    {
        return sprintf(
            'Direct manuel du %s - %s',
            $startsAt->format('d/m/Y'),
            $categoryTitle
        );
    }

    private function buildDescription(
        string $categoryTitle,
        \DateTimeInterface $startsAt,
        bool $generatedFromGrid
    ): string {
        if ($generatedFromGrid) {
            return sprintf(
                "Émission en direct du %s à %s, générée automatiquement depuis la grille de programmation pour la catégorie « %s ».\n\nCette fiche doit être complétée après l’émission.",
                $startsAt->format('d/m/Y'),
                $startsAt->format('H:i'),
                $categoryTitle
            );
        }

        return sprintf(
            "Émission en direct du %s à %s, créée manuellement depuis la grille de programmation pour la catégorie « %s ».\n\nCette fiche doit être complétée après l’émission.",
            $startsAt->format('d/m/Y'),
            $startsAt->format('H:i'),
            $categoryTitle
        );
    }
}
