vich_uploader:
    db_driver: orm

    mappings:
        emissions:
            uri_prefix: /uploads/images/emissions
            upload_destination: '%kernel.project_dir%/public/uploads/images/emissions'
            namer:
                service: App\Service\SafeFilenameNamer
                options: { property: 'titre' }
        categories:
            uri_prefix: /uploads/images/categories
            upload_destination: '%kernel.project_dir%/public/uploads/images/categories'
            namer:
                service: App\Service\SafeFilenameNamer
                options: { property: 'titre' }
        themes:
            uri_prefix: /uploads/images/theme
            upload_destination: '%kernel.project_dir%/public/uploads/images/theme'
            namer:
                service: App\Service\SafeFilenameNamer
                options: { property: 'name'} 
        annonces:
            uri_prefix: /uploads/images/annonce
            upload_destination: '%kernel.project_dir%/public/uploads/images/annonce'
            namer:
                service: App\Service\SafeFilenameNamer
                options: { property: 'titre'}     
        emissionsMp3:
            uri_prefix: /uploads/emissionsMp3
            upload_destination: '%kernel.project_dir%/public/uploads/emissionsMp3'
            namer:
                service: App\Service\SafeFilenameNamer
                options: { property: 'titre' }
        evenements:
            uri_prefix: /uploads/images/evenement
            upload_destination: '%kernel.project_dir%/public/uploads/images/evenement'
            namer:
                service: App\Service\SafeFilenameNamer
                options: { property: 'titre'}
        page_main_image:
            uri_prefix: /uploads/pages
            upload_destination: '%kernel.project_dir%/public/uploads/pages'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        categorie_tag_images:
            uri_prefix: /uploads/tag-images
            upload_destination: '%kernel.project_dir%/public/uploads/tag-images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        site_images:
            uri_prefix: /uploads/images/site
            upload_destination: '%kernel.project_dir%/public/uploads/images/site'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true