<?php

namespace App\Tests\Entity;

use App\Entity\Categories;
use App\Entity\Diffusion;
use App\Entity\Editeur;
use App\Entity\Emission;
use App\Entity\InviteOldAnimateur;
use App\Entity\ProgrammationRuleSlot;
use App\Entity\Theme;
use App\Entity\User;
use PHPUnit\Framework\TestCase;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use Symfony\Component\Validator\Violation\ConstraintViolationBuilderInterface;

class EmissionTest extends TestCase
{
    public function testInitialValues(): void
    {
        $emission = new Emission();

        $this->assertNull($emission->getId());

        $this->assertSame('', $emission->getTitre());
        $this->assertSame('', $emission->getKeyword());
        $this->assertNull($emission->getDatepub());
        $this->assertNull($emission->getRef());
        $this->assertNull($emission->getDuree());
        $this->assertNull($emission->getUrl());
        $this->assertSame('', $emission->getDescriptif());

        $this->assertFalse($emission->isAutoGenerated());
        $this->assertFalse($emission->isPendingCompletion());
        $this->assertFalse($emission->isLive());

        $this->assertNull($emission->getCategorie());
        $this->assertNull($emission->getTheme());
        $this->assertNull($emission->getEditeur());

        $this->assertNull($emission->getThumbnail());
        $this->assertNull($emission->getThumbnailFile());
        $this->assertNull($emission->getThumbnailMp3());
        $this->assertNull($emission->getThumbnailFileMp3());
        $this->assertNull($emission->getUpdatedat());

        $this->assertCount(0, $emission->getUsers());
        $this->assertNull($emission->getUser());

        $this->assertCount(0, $emission->getInviteOldAnimateurs());
        $this->assertCount(0, $emission->getDiffusions());

        $this->assertNull($emission->getLastDiffusion());
        $this->assertNull($emission->getNextDiffusion());
        $this->assertNull($emission->getDerniereDiffusion());

        $this->assertNull($emission->getAutoGeneratedForSlot());
        $this->assertNull($emission->getAutoGeneratedForStartsAt());

        $this->assertNull($emission->getDeletedAt());
        $this->assertFalse($emission->isDeleted());
    }

    public function testBasicSettersAndGetters(): void
    {
        $emission = new Emission();

        $datepub = new \DateTime('2023-01-01 12:00:00');
        $updatedAt = new \DateTime('2023-02-01 14:30:00');

        $emission
            ->setTitre('Titre test')
            ->setKeyword('motclé')
            ->setDatepub($datepub)
            ->setRef('REF-123')
            ->setDuree(150)
            ->setUrl('https://example.com/audio.mp3')
            ->setDescriptif('Une belle description')
            ->setThumbnail('image.jpg')
            ->setThumbnailMp3('audio.mp3')
            ->setUpdatedat($updatedAt);

        $this->assertSame('Titre test', $emission->getTitre());
        $this->assertSame('motclé', $emission->getKeyword());
        $this->assertSame($datepub, $emission->getDatepub());
        $this->assertSame('REF-123', $emission->getRef());
        $this->assertSame(150, $emission->getDuree());
        $this->assertSame(
            'https://example.com/audio.mp3',
            $emission->getUrl()
        );
        $this->assertSame(
            'Une belle description',
            $emission->getDescriptif()
        );
        $this->assertSame('image.jpg', $emission->getThumbnail());
        $this->assertSame('audio.mp3', $emission->getThumbnailMp3());
        $this->assertSame($updatedAt, $emission->getUpdatedat());
    }

    public function testNullableSetters(): void
    {
        $emission = new Emission();

        $emission
            ->setKeyword('test')
            ->setUrl('https://example.com')
            ->setThumbnail('image.jpg')
            ->setThumbnailMp3('audio.mp3');

        $emission
            ->setKeyword(null)
            ->setUrl(null)
            ->setThumbnail(null)
            ->setThumbnailMp3(null);

        $this->assertNull($emission->getKeyword());
        $this->assertNull($emission->getUrl());
        $this->assertNull($emission->getThumbnail());
        $this->assertNull($emission->getThumbnailMp3());
    }

    public function testThumbnailIsTrimmed(): void
    {
        $emission = new Emission();

        $emission->setThumbnail('  image.jpg  ');

        $this->assertSame('image.jpg', $emission->getThumbnail());
    }

    public function testSetThumbnailFileUpdatesUpdatedAt(): void
    {
        $file = $this->createMock(File::class);

        $emission = new Emission();

        $this->assertNull($emission->getUpdatedat());

        $emission->setThumbnailFile($file);

        $this->assertSame($file, $emission->getThumbnailFile());
        $this->assertInstanceOf(
            \DateTimeInterface::class,
            $emission->getUpdatedat()
        );
    }

    public function testSetThumbnailFileToNullDoesNotUpdateUpdatedAt(): void
    {
        $emission = new Emission();

        $emission->setThumbnailFile(null);

        $this->assertNull($emission->getThumbnailFile());
        $this->assertNull($emission->getUpdatedat());
    }

    public function testSetThumbnailFileMp3UpdatesUpdatedAt(): void
    {
        $file = $this->createMock(File::class);

        $emission = new Emission();

        $this->assertNull($emission->getUpdatedat());

        $emission->setThumbnailFileMp3($file);

        $this->assertSame($file, $emission->getThumbnailFileMp3());
        $this->assertInstanceOf(
            \DateTimeInterface::class,
            $emission->getUpdatedat()
        );
    }

    public function testSetThumbnailFileMp3ToNullDoesNotUpdateUpdatedAt(): void
    {
        $emission = new Emission();

        $emission->setThumbnailFileMp3(null);

        $this->assertNull($emission->getThumbnailFileMp3());
        $this->assertNull($emission->getUpdatedat());
    }

    public function testSimpleRelations(): void
    {
        $emission = new Emission();

        $theme = $this->createMock(Theme::class);
        $categorie = $this->createMock(Categories::class);
        $editeur = $this->createMock(Editeur::class);

        $emission
            ->setTheme($theme)
            ->setCategorie($categorie)
            ->setEditeur($editeur);

        $this->assertSame($theme, $emission->getTheme());
        $this->assertSame($categorie, $emission->getCategorie());
        $this->assertSame($editeur, $emission->getEditeur());

        $emission
            ->setTheme(null)
            ->setCategorie(null)
            ->setEditeur(null);

        $this->assertNull($emission->getTheme());
        $this->assertNull($emission->getCategorie());
        $this->assertNull($emission->getEditeur());
    }

    public function testAddAndRemoveUsers(): void
    {
        $emission = new Emission();

        $user1 = $this->createMock(User::class);
        $user2 = $this->createMock(User::class);

        $emission->addUser($user1);
        $emission->addUser($user2);

        $this->assertCount(2, $emission->getUsers());
        $this->assertTrue($emission->getUsers()->contains($user1));
        $this->assertTrue($emission->getUsers()->contains($user2));

        $emission->removeUser($user1);

        $this->assertCount(1, $emission->getUsers());
        $this->assertFalse($emission->getUsers()->contains($user1));
        $this->assertTrue($emission->getUsers()->contains($user2));
    }

    public function testAddingSameUserTwiceDoesNotDuplicateIt(): void
    {
        $emission = new Emission();
        $user = $this->createMock(User::class);

        $emission->addUser($user);
        $emission->addUser($user);

        $this->assertCount(1, $emission->getUsers());
    }

    public function testLegacyGetUserReturnsFirstUser(): void
    {
        $emission = new Emission();

        $user1 = $this->createMock(User::class);
        $user2 = $this->createMock(User::class);

        $emission->addUser($user1);
        $emission->addUser($user2);

        $this->assertSame($user1, $emission->getUser());
    }

    public function testLegacySetUserReplacesExistingUsers(): void
    {
        $emission = new Emission();

        $user1 = $this->createMock(User::class);
        $user2 = $this->createMock(User::class);

        $emission->addUser($user1);
        $emission->setUser($user2);

        $this->assertCount(1, $emission->getUsers());
        $this->assertSame($user2, $emission->getUser());
        $this->assertFalse($emission->getUsers()->contains($user1));
    }

    public function testLegacySetUserNullClearsUsers(): void
    {
        $emission = new Emission();
        $user = $this->createMock(User::class);

        $emission->addUser($user);

        $emission->setUser(null);

        $this->assertCount(0, $emission->getUsers());
        $this->assertNull($emission->getUser());
    }

    public function testAddAndRemoveInviteOldAnimateur(): void
    {
        $emission = new Emission();

        $invite = $this->createMock(InviteOldAnimateur::class);

        $emission->addInviteOldAnimateur($invite);

        $this->assertCount(1, $emission->getInviteOldAnimateurs());
        $this->assertTrue(
            $emission->getInviteOldAnimateurs()->contains($invite)
        );

        $emission->removeInviteOldAnimateur($invite);

        $this->assertCount(0, $emission->getInviteOldAnimateurs());
    }

    public function testAddingSameInviteOldAnimateurTwiceDoesNotDuplicateIt(): void
    {
        $emission = new Emission();
        $invite = $this->createMock(InviteOldAnimateur::class);

        $emission->addInviteOldAnimateur($invite);
        $emission->addInviteOldAnimateur($invite);

        $this->assertCount(1, $emission->getInviteOldAnimateurs());
    }

    public function testAutoGeneratedState(): void
    {
        $emission = new Emission();

        $emission->setIsAutoGenerated(true);

        $this->assertTrue($emission->isAutoGenerated());

        $emission->setIsAutoGenerated(false);

        $this->assertFalse($emission->isAutoGenerated());
    }

    public function testPendingCompletionState(): void
    {
        $emission = new Emission();

        $emission->setIsPendingCompletion(true);

        $this->assertTrue($emission->isPendingCompletion());

        $emission->setIsPendingCompletion(false);

        $this->assertFalse($emission->isPendingCompletion());
    }

    public function testLiveState(): void
    {
        $emission = new Emission();

        $emission->setIsLive(true);

        $this->assertTrue($emission->isLive());

        $emission->setIsLive(false);

        $this->assertFalse($emission->isLive());
    }

    public function testMarkAsAutoGeneratedSetsExpectedStates(): void
    {
        $emission = new Emission();

        $result = $emission->markAsAutoGenerated();

        $this->assertSame($emission, $result);
        $this->assertTrue($emission->isAutoGenerated());
        $this->assertTrue($emission->isLive());
        $this->assertTrue($emission->isPendingCompletion());
    }

    public function testMarkAsCompletedOnlyClearsPendingCompletion(): void
    {
        $emission = new Emission();

        $emission->markAsAutoGenerated();

        $result = $emission->markAsCompleted();

        $this->assertSame($emission, $result);
        $this->assertFalse($emission->isPendingCompletion());

        $this->assertTrue($emission->isAutoGenerated());
        $this->assertTrue($emission->isLive());
    }

    public function testAddDiffusionSetsEmission(): void
    {
        $emission = new Emission();

        $diffusion = $this->createMock(Diffusion::class);

        $diffusion
            ->expects($this->once())
            ->method('setEmission')
            ->with($emission);

        $emission->addDiffusion($diffusion);

        $this->assertCount(1, $emission->getDiffusions());
        $this->assertTrue(
            $emission->getDiffusions()->contains($diffusion)
        );
    }

    public function testAddingSameDiffusionTwiceDoesNotDuplicateIt(): void
    {
        $emission = new Emission();

        $diffusion = $this->createMock(Diffusion::class);

        $diffusion
            ->expects($this->once())
            ->method('setEmission')
            ->with($emission);

        $emission->addDiffusion($diffusion);
        $emission->addDiffusion($diffusion);

        $this->assertCount(1, $emission->getDiffusions());
    }

    public function testRemoveDiffusionClearsOwningSide(): void
    {
        $emission = new Emission();

        $diffusion = $this->createMock(Diffusion::class);

        $diffusion
            ->expects($this->exactly(2))
            ->method('setEmission')
            ->withConsecutive(
                [$emission],
                [null]
            );

        $diffusion
            ->expects($this->once())
            ->method('getEmission')
            ->willReturn($emission);

        $emission->addDiffusion($diffusion);
        $emission->removeDiffusion($diffusion);

        $this->assertCount(0, $emission->getDiffusions());
    }

    public function testRemoveDiffusionDoesNotClearDifferentOwningSide(): void
    {
        $emission = new Emission();
        $otherEmission = new Emission();

        $diffusion = $this->createMock(Diffusion::class);

        $diffusion
            ->expects($this->once())
            ->method('setEmission')
            ->with($emission);

        $diffusion
            ->expects($this->once())
            ->method('getEmission')
            ->willReturn($otherEmission);

        $emission->addDiffusion($diffusion);
        $emission->removeDiffusion($diffusion);

        $this->assertCount(0, $emission->getDiffusions());
    }

    public function testDerniereDiffusionReturnsLatestDate(): void
    {
        $emission = new Emission();

        $date1 = new \DateTime('2026-01-10 10:00:00');
        $date2 = new \DateTime('2026-01-12 14:00:00');
        $date3 = new \DateTime('2026-01-11 18:00:00');

        $diffusion1 = $this->createMock(Diffusion::class);
        $diffusion2 = $this->createMock(Diffusion::class);
        $diffusion3 = $this->createMock(Diffusion::class);

        $diffusion1
            ->method('getHoraireDiffusion')
            ->willReturn($date1);

        $diffusion2
            ->method('getHoraireDiffusion')
            ->willReturn($date2);

        $diffusion3
            ->method('getHoraireDiffusion')
            ->willReturn($date3);

        $diffusion1->method('setEmission');
        $diffusion2->method('setEmission');
        $diffusion3->method('setEmission');

        $emission->addDiffusion($diffusion1);
        $emission->addDiffusion($diffusion2);
        $emission->addDiffusion($diffusion3);

        $this->assertSame(
            $date2,
            $emission->getDerniereDiffusion()
        );
    }

    public function testDerniereDiffusionIgnoresNullDates(): void
    {
        $emission = new Emission();

        $date = new \DateTime('2026-01-12 14:00:00');

        $withoutDate = $this->createMock(Diffusion::class);
        $withDate = $this->createMock(Diffusion::class);

        $withoutDate
            ->method('getHoraireDiffusion')
            ->willReturn(null);

        $withDate
            ->method('getHoraireDiffusion')
            ->willReturn($date);

        $withoutDate->method('setEmission');
        $withDate->method('setEmission');

        $emission->addDiffusion($withoutDate);
        $emission->addDiffusion($withDate);

        $this->assertSame(
            $date,
            $emission->getDerniereDiffusion()
        );
    }

    public function testLastAndNextDiffusion(): void
    {
        $emission = new Emission();

        $last = new \DateTime('2026-01-01 10:00:00');
        $next = new \DateTime('2026-01-08 10:00:00');

        $emission
            ->setLastDiffusion($last)
            ->setNextDiffusion($next);

        $this->assertSame($last, $emission->getLastDiffusion());
        $this->assertSame($next, $emission->getNextDiffusion());

        $emission
            ->setLastDiffusion(null)
            ->setNextDiffusion(null);

        $this->assertNull($emission->getLastDiffusion());
        $this->assertNull($emission->getNextDiffusion());
    }

    public function testAutoGeneratedSlotAndStartsAt(): void
    {
        $emission = new Emission();

        $slot = $this->createMock(ProgrammationRuleSlot::class);
        $startsAt = new \DateTime('2026-09-08 14:00:00');

        $emission
            ->setAutoGeneratedForSlot($slot)
            ->setAutoGeneratedForStartsAt($startsAt);

        $this->assertSame(
            $slot,
            $emission->getAutoGeneratedForSlot()
        );

        $this->assertSame(
            $startsAt,
            $emission->getAutoGeneratedForStartsAt()
        );

        $emission
            ->setAutoGeneratedForSlot(null)
            ->setAutoGeneratedForStartsAt(null);

        $this->assertNull($emission->getAutoGeneratedForSlot());
        $this->assertNull(
            $emission->getAutoGeneratedForStartsAt()
        );
    }

    public function testSoftDeleteAndRestore(): void
    {
        $emission = new Emission();

        $this->assertFalse($emission->isDeleted());
        $this->assertNull($emission->getDeletedAt());

        $result = $emission->softDelete();

        $this->assertSame($emission, $result);
        $this->assertTrue($emission->isDeleted());
        $this->assertInstanceOf(
            \DateTimeImmutable::class,
            $emission->getDeletedAt()
        );

        $result = $emission->restore();

        $this->assertSame($emission, $result);
        $this->assertFalse($emission->isDeleted());
        $this->assertNull($emission->getDeletedAt());
    }

    public function testValidationPassesWhenEmissionHasUser(): void
    {
        $emission = new Emission();

        $user = $this->createMock(User::class);
        $context = $this->createMock(ExecutionContextInterface::class);

        $emission->addUser($user);

        $context
            ->expects($this->never())
            ->method('buildViolation');

        $emission->validateOwnerOrFormerHost($context);
    }

    public function testValidationPassesWhenEmissionHasFormerHost(): void
    {
        $emission = new Emission();

        $invite = $this->createMock(InviteOldAnimateur::class);

        $invite
            ->expects($this->once())
            ->method('isAncienanimateur')
            ->willReturn(true);

        $emission->addInviteOldAnimateur($invite);

        $context = $this->createMock(
            ExecutionContextInterface::class
        );

        $context
            ->expects($this->never())
            ->method('buildViolation');

        $emission->validateOwnerOrFormerHost($context);
    }

    public function testValidationAddsViolationsWithoutUserOrFormerHost(): void
    {
        $emission = new Emission();

        $context = $this->createMock(
            ExecutionContextInterface::class
        );

        $builderUsers = $this->createMock(
            ConstraintViolationBuilderInterface::class
        );

        $builderInvites = $this->createMock(
            ConstraintViolationBuilderInterface::class
        );

        $message =
            'Il faut sélectionner au moins un·e utilisateur·ice ' .
            'ou un·e ancien·ne animateur·ice.';

        $context
            ->expects($this->exactly(2))
            ->method('buildViolation')
            ->with($message)
            ->willReturnOnConsecutiveCalls(
                $builderUsers,
                $builderInvites
            );

        $builderUsers
            ->expects($this->once())
            ->method('atPath')
            ->with('users')
            ->willReturnSelf();

        $builderUsers
            ->expects($this->once())
            ->method('addViolation');

        $builderInvites
            ->expects($this->once())
            ->method('atPath')
            ->with('inviteOldAnimateurs')
            ->willReturnSelf();

        $builderInvites
            ->expects($this->once())
            ->method('addViolation');

        $emission->validateOwnerOrFormerHost($context);
    }

    public function testNonFormerInviteDoesNotSatisfyValidation(): void
    {
        $emission = new Emission();

        $invite = $this->createMock(InviteOldAnimateur::class);

        $invite
            ->expects($this->once())
            ->method('isAncienanimateur')
            ->willReturn(false);

        $emission->addInviteOldAnimateur($invite);

        $context = $this->createMock(
            ExecutionContextInterface::class
        );

        $builderUsers = $this->createMock(
            ConstraintViolationBuilderInterface::class
        );

        $builderInvites = $this->createMock(
            ConstraintViolationBuilderInterface::class
        );

        $context
            ->expects($this->exactly(2))
            ->method('buildViolation')
            ->willReturnOnConsecutiveCalls(
                $builderUsers,
                $builderInvites
            );

        $builderUsers
            ->method('atPath')
            ->willReturnSelf();

        $builderInvites
            ->method('atPath')
            ->willReturnSelf();

        $emission->validateOwnerOrFormerHost($context);
    }
}